name: Development Environment CI

on:
  push:
    branches: [ dev, development ]
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'supabase/**'
      - 'scripts/**'
      - 'lib/supabase*'

env:
  NODE_ENV: development

jobs:
  verify-environments:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        cat > .env.local << EOF
        NODE_ENV=development
        NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_PROD_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_PROD_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_PROD_SERVICE_KEY }}
        NEXT_PUBLIC_SUPABASE_DEV_URL=${{ secrets.SUPABASE_DEV_URL }}
        NEXT_PUBLIC_SUPABASE_DEV_ANON_KEY=${{ secrets.SUPABASE_DEV_ANON_KEY }}
        SUPABASE_DEV_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_DEV_SERVICE_KEY }}
        EOF
        
    - name: Verify environment configuration
      run: npm run verify-environments
      
    - name: Test development environment
      run: npm run verify-environments -- --env=development
      
    - name: Validate schema migration
      run: npm run migrate-to-dev -- --schema-only
      
    - name: Test seed data
      run: npm run seed-dev
      
    - name: Build application (development)
      run: npm run build:dev
      
  test-production-compatibility:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        cat > .env.local << EOF
        NODE_ENV=production
        NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_PROD_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_PROD_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_PROD_SERVICE_KEY }}
        EOF
        
    - name: Test production environment (read-only)
      run: npm run verify-environments -- --env=production
      
    - name: Build application (production)
      run: npm run build
